name: Run Typescript tests

on:
  push:
    branches:
      - main
    paths:
      - 'typescript/**'
  pull_request:
    types:
      - opened
      - edited
  workflow_dispatch:

permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: typescript
    steps:
      - name: Checkout repository
        uses: actions/checkout@9a9194f87191a7e9055e3e9b95b8cfb13023bb08

      - name: Link Checker
        uses: lycheeverse/lychee-action@c053181aa0c3d17606addfe97a9075a32723548a
        with:
          fail: true
          args: --scheme=https . --exclude-all-private --accept 999
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run coverage