name: Run security checks on the project
on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: typescript
    env:
      ACTIONS_STEP_DEBUG: true
    steps:
      # Checkout and setup.
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm install

      # NPM audit.
      - name: Run audit
        run: npm audit
        continue-on-error: true

      # GitLeaks.
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
